language: php

sudo: false

php:
  # 5.4
  # 5.5
  - 5.6
  # 7
  # hhvm

install:
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpcs --colors --standard=.travis/phpcs-ruleset.xml -n src/
  # php vendor/bin/phpcs -s --colors --standard=.travis/phpcs-ruleset.xml -n src/
  - php vendor/bin/phpmd src/ text naming,codesize,design,unusedcode
  - php vendor/bin/phpcpd src/